#!/usr/bin/env bash

# git config --global alias.diffi '!git diff'
_git_root=$(git rev-parse --show-toplevel)

DIFFIGNORE_GLOBAL=${DIFFIGNORE_GLOBAL:-~/.diffignore.global}

# Only use colors if connected to a terminal
if [ -t 1 ]; then
    RED=$(printf '\033[31m')
    RESET=$(printf '\033[m')
    YELLOW=$(printf '\033[33m')
else
    RED=""
    RESET=""
    YELLOW=""
fi

error() {
	echo ${RED}"Error: $@"${RESET} >&2
}

arg_init() {
    DIFFI_SOURCE="$DIFFIGNORE_GLOBAL"
    DIFFI_DEST="$_git_root/.diffignore" 

    if [[ "$1" == "--base" ]]; then
        DIFFI_DEST="$_git_root/.diffignore.base" 
    fi

    test -e "$DIFFIGNORE_GLOBAL" || {
        error "$DIFFIGNORE_GLOBAL does not exist" 
        exit 1
    }

    test ! -e "$DIFFI_DEST" || {
        error "$DIFFI_DEST already exists!" 
        exit 1
    }

    cp "$DIFFI_SOURCE" "$DIFFI_DEST" || {
        error "failed to create .diffignore.base"
        exit 1
    }

    echo "${DIFFI_DEST##*/} created in project root"
    echo 
    echo "${YELLOW}Please add ${RESET}.diffignore${YELLOW} to the project ${RESET}.gitignore${YELLOW} if you have not done so"
}

diffi_init(){
    test -e "$_git_root/.diffignore" || {
        cp "$_git_root/.diffignore.base" "$_git_root/.diffignore" >& /dev/null || \
        error "no .diffignore or .diffignore.base found in root git directory!"
        echo "    $ git diffi (--init | --init-base)"
        exit 1
    }
}

case "$1" in
    "--init") arg_init; exit 0 ;;
    "--init-base") arg_init --base; exit 0 ;;
esac

# standard init fallthrough
diffi_init


PATHS=()
VALID_ARGS=()

while (( "$#" )); do
    # swallow double dash since we will append it anyways
    if [[ "$1" == "--" ]]; then
        continue
    # determine valid glob patterns also checks existence of strict path
    elif [[ $(compgen -G "$1") ]]; then
        PATHS+=("$1")
    else
        VALID_ARGS+=("$1")
    fi
shift
done

# https://git-scm.com/docs/gitignore#_pattern_format
DIFFI=()

# read from .diffignore file
while read -r ignore; do
    if [ -n "$ignore" ] && [[ "${ignore}" != \!* ]] && [[ "$ignore" != \#* ]] ;
    then
        DIFFI+=(":!${ignore}")
    fi
done < "$_git_root/.diffignore"



[[ -n "$PATHS" ]] && REAL_PATHS=$(realpath --relative-to=$_git_root ${PATHS[@]})
# execute git diff from repo root so that diffignore is applied properly
# keeping provided direct paths
(cd "$_git_root" || exit 1; \
    git diff $(echo "${VALID_ARGS[@]} --  ${REAL_PATHS:-} ${DIFFI[@]}"))
